---
- name: Install epel-release and yum-utils with yum
  yum:
    name:
      - epel-release
      - yum-utils
    state: present

- name: Install remi-release 7 and enable remi-php73 with yum
  yum: 
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present
    enablerepo: "remi-php73"

- name: Install lot of php packages with yum
  yum:
    name:
      - php
      - php-common
      - php-opcache
      - php-mcrypt
      - php-cli
      - php-gd
      - php-curl
      - php-mysqlnd

- name: Update httpd
  yum:
    name: httpd
    state: latest
